I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 544, in script call
    call celine_party
  File "game/script.rpy", line 1102, in script
    "But after the dumpster-fire encounter with Cliff, her reservations have gone down from 95% to maybe 30%."
ValueError: unsupported format character 't' (0x74) at index 91

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 544, in script call
    call celine_party
  File "game/script.rpy", line 1102, in script
    "But after the dumpster-fire encounter with Cliff, her reservations have gone down from 95% to maybe 30%."
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 991, in execute
    renpy.exports.say(who, what, *args, **kwargs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/sayexports.py", line 118, in say
    what = what % tag_quoting_dict
           ~~~~~^~~~~~~~~~~~~~~~~~
ValueError: unsupported format character 't' (0x74) at index 91

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
Still Heart 1.0
Sat Sep 27 12:20:56 2025
