I'm sorry, but an uncaught exception occurred.

While running game code:
NameError: name 'text' is not defined. Did you mean: 'Text'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 742, in script
    text "Thanks for playing!"
Exception: Sayer 'text' is not defined.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'text' is not defined. Did you mean: 'Text'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 742, in script
    text "Thanks for playing!"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'text' is not defined.

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
Still Heart 1.0
Sun Sep 28 18:21:14 2025
